-- MySQL Script generated by MySQL Workbench
-- Пнд 03 июн 2019 17:32:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carriage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carriage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carriage` DEFAULT CHARACTER SET utf8 ;
USE `carriage` ;

-- -----------------------------------------------------
-- Table `carriage`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carriage`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `weight` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_1`
    FOREIGN KEY (`userId`)
    REFERENCES `carriage`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carriage`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`addresses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `orderId` INT(11) NOT NULL,
  `addressSent` VARCHAR(100) NOT NULL,
  `deliveryAddress` VARCHAR(100) NOT NULL,
  `distance` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_addresses_1_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_1`
    FOREIGN KEY (`orderId`)
    REFERENCES `carriage`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carriage`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`invoices` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `orderId` INT(11) NOT NULL,
  `sum` INT(11) NOT NULL,
  `state` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoices_1_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_1`
    FOREIGN KEY (`orderId`)
    REFERENCES `carriage`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carriage`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `message` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
