-- MySQL Script generated by MySQL Workbench
-- Птн 24 мая 2019 16:19:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carriage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carriage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carriage` DEFAULT CHARACTER SET utf8 ;
USE `carriage` ;

-- -----------------------------------------------------
-- Table `carriage`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carriage`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `weight` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `carriage`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carriage`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`addresses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `address_sent` VARCHAR(100) NOT NULL,
  `delivery_address` VARCHAR(100) NOT NULL,
  `distance` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_addresses_1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `carriage`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carriage`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`invoices` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `sum` INT(11) NOT NULL,
  `state` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoices_1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `carriage`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carriage`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carriage`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roles_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `carriage`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
